/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__dataguzzler_python__dgold
#define __PYX_HAVE__dataguzzler_python__dgold


#ifndef __PYX_HAVE_API__dataguzzler_python__dgold

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(struct AtExitFunc) *AddAtExitFunc(void (*)(struct AtExitFunc *, void *), void *);

__PYX_EXTERN_C DL_IMPORT(char) *SetQueryPrefix;
__PYX_EXTERN_C DL_IMPORT(char) *SetQueryPostfix;
__PYX_EXTERN_C DL_IMPORT(int) dg_PosixClock;
__PYX_EXTERN_C DL_IMPORT(struct Module) *DefaultModule;
__PYX_EXTERN_C DL_IMPORT(char) *commandname;
__PYX_EXTERN_C DL_IMPORT(struct dgl_List) InitActionList;
__PYX_EXTERN_C DL_IMPORT(struct dgl_List) ConnList;
__PYX_EXTERN_C DL_IMPORT(struct dgl_List) ModuleList;

#endif /* !__PYX_HAVE_API__dataguzzler_python__dgold */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initdgold(void);
#else
PyMODINIT_FUNC PyInit_dgold(void);
#endif

#endif /* !__PYX_HAVE__dataguzzler_python__dgold */
